name: dsc180b
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.0
  - pandas==2.1.4
  - numpy==1.26.2
  - scikit-learn==1.3.2
  - matplotlib==3.8.2
  - pyarrow==12.0.0
  - xgboost==2.0.3
  - shap==0.42.1